import { LessonQuestion, LessonSection } from './lesson.model';

export interface DetailedLessonContent {
  sections: LessonSection[];
  questions: LessonQuestion[];
}

const q = (question: string, options: string[], answer: number, explanation: string): LessonQuestion => ({ question, options, answer, explanation });

export const detailedLessonContent: Record<number, DetailedLessonContent> = {
  1: {
    sections: [
      { title: 'What Angular is', explanation: 'Angular is a TypeScript framework for building complete web applications. It gives you a component model for the screen, a template language for HTML, dependency injection for shared work, a router for screens, forms for user input, HttpClient for APIs, and testing tools. A framework makes decisions with you: the project has a predictable shape, and different developers can understand each other’s code.', example: `ng new angular-atlas --routing\ncd angular-atlas\nng serve\n\n// The browser loads the root component first.\nbootstrapApplication(AppComponent, appConfig);`, notes: ['Angular is not the same thing as AngularJS.', 'Angular applications are normally compiled before users download them.', 'Standalone components are the modern default; NgModules still exist in older applications.'] },
      { title: 'How an Angular app starts', explanation: 'The browser loads src/index.html. src/main.ts calls bootstrapApplication and starts one root component. That root component renders its template, and its template can contain child components. This creates a component tree. Data generally flows down through inputs and user intent flows up through outputs or shared services.', example: `// src/main.ts\nimport { bootstrapApplication } from '@angular/platform-browser';\nimport { AppComponent } from './app/app.component';\n\nbootstrapApplication(AppComponent, appConfig);\n\n// app.component.html\n<app-header />\n<app-course-list />`, notes: ['The root component is not the whole application forever; it is only the entry point.', 'A route can replace the content inside router-outlet.'] },
      { title: 'Angular building blocks', explanation: 'Components render UI. Templates describe HTML and bindings. Directives add behavior. Pipes format values. Services hold reusable logic. Dependency injection supplies services. Routes map URLs to screens. Signals and Observables model values that change over time. Learn these as cooperating parts rather than isolated vocabulary.', example: `Component -> template -> child component\n       |                  |\n       +--> service <------+\n              |\n              +--> HttpClient -> API`, notes: ['Start with components and templates before learning global state.', 'A good feature usually combines several small building blocks.'] },
      { title: 'Angular CLI workflow', explanation: 'Use the CLI to generate consistent files and run the same checks every time. ng serve gives a development server, ng generate creates code, ng build makes a production bundle, and ng test runs unit tests. Read the generated files rather than treating CLI output as magic.', example: `ng generate component courses/course-card\nng generate service courses/data-access/course\nng build --configuration production\nnpm test`, notes: ['Generated code is a starting point, not a finished design.', 'Commit configuration changes so teammates use the same project rules.'] }
    ],
    questions: [
      q('What starts an Angular application in a modern standalone app?', ['bootstrapApplication', 'new XMLHttpRequest', 'routerLink'], 0, 'main.ts calls bootstrapApplication with the root component and application configuration.'),
      q('Which building block owns a piece of the screen?', ['A component', 'An environment file', 'An npm script'], 0, 'A component combines a class, template, styles, and metadata for one UI responsibility.'),
      q('What is the main benefit of a framework like Angular?', ['A consistent structure for complete apps', 'It removes the need for HTML', 'It stores data permanently'], 0, 'Angular supplies conventions and tools for UI, navigation, data access, forms, and testing.')
    ]
  },
  2: {
    sections: [
      { title: 'What makes a component', explanation: 'A component is a TypeScript class plus Angular metadata and a view. Its class owns state and behavior. Its template displays that state. Its style sheet controls presentation. Metadata tells Angular the selector, template, styles, providers, imports, and change detection strategy.', example: `@Component({\n  selector: 'app-profile-card',\n  standalone: true,\n  imports: [AvatarComponent],\n  templateUrl: './profile-card.html',\n  styleUrl: './profile-card.css'\n})\nexport class ProfileCard {\n  name = 'Ada Lovelace';\n}`, notes: ['Use a specific selector such as app-profile-card.', 'Keep the class focused on the component’s visible responsibility.'] },
      { title: 'Types of components', explanation: 'There are several useful ways to classify components. A root or shell component owns the application frame. A routed page component represents a URL. A presentational component receives data and emits events. A container or smart component coordinates services and state. A layout component arranges children. These are roles, not separate Angular APIs, and one component should not try to perform every role.', example: `// Presentational: inputs in, output out\n<app-course-card\n  [course]="course"\n  (open)="openCourse($event)" />\n\n// Container: owns data and coordination\ncourses = inject(CourseStore).courses;`, notes: ['Prefer small presentational components for repeated UI.', 'Pages can coordinate; leaf components should not know the whole application.'] },
      { title: 'Selectors and component reuse', explanation: 'The selector is the public HTML name of a component. Element selectors are easiest to read: app-course-card. Attribute selectors can enhance an existing element, but that is more commonly a directive. A component is reusable when its inputs describe what it needs and its outputs describe what happened, without depending on a parent’s private fields.', example: `@Component({ selector: 'app-alert', ... })\nexport class Alert {\n  type = input<'info' | 'error'>('info');\n  dismissed = output<void>();\n}\n\n<app-alert type="error" (dismissed)="close()" />`, notes: ['Do not use a component selector that looks like a native HTML element.', 'Keep public input names stable because many templates may use them.'] },
      { title: 'Standalone components and imports', explanation: 'A standalone component declares its own imports instead of being declared by an NgModule. If a template uses another component, a pipe, or a directive, import it in the component metadata. This makes dependencies visible at the point of use and makes lazy loading easier.', example: `@Component({\n  standalone: true,\n  imports: [RouterLink, DatePipe, CourseCard],\n  template: ` + "`" + `<a routerLink="/courses">{{ today | date }}</a>` + "`" + `\n})\nexport class CourseHome {}`, notes: ['A missing template import usually appears as a compiler error.', 'Do not import an entire module when one small standalone dependency is enough.'] },
      { title: 'Component lifecycle', explanation: 'A component is created, receives inputs, renders, may update many times, and is destroyed. Use initialization hooks only for work that depends on Angular lifecycle timing. Use ngOnDestroy or takeUntilDestroyed for cleanup. Most simple state derivation belongs in signals and computed values rather than lifecycle hooks.', example: `export class Timer implements OnDestroy {\n  private timer = setInterval(() => this.tick(), 1000);\n\n  ngOnDestroy() {\n    clearInterval(this.timer);\n  }\n}`, notes: ['Do not use ngOnInit just because it exists; field initialization may be enough.', 'Destroy subscriptions, timers, observers, and third-party widgets.'] }
    ],
    questions: [
      q('Which component role usually receives data and emits user intent?', ['Presentational component', 'Database component', 'Environment component'], 0, 'Presentational components are easier to reuse because they do not own the whole application state.'),
      q('Where does a standalone component list a pipe it uses?', ['Its imports metadata', 'The browser console', 'package-lock.json'], 0, 'Standalone dependencies are imported directly in the component metadata.'),
      q('What should happen when a component is destroyed?', ['Owned resources should be cleaned up', 'All application state must be deleted', 'The browser must reload'], 0, 'Cleanup prevents timers, subscriptions, and DOM integrations from leaking.')
    ]
  },
  3: {
    sections: [
      { title: 'Interpolation: text from class to template', explanation: 'Interpolation uses double curly braces to place a value into text content. Angular evaluates the expression and converts the result to a string. It is ideal for headings, labels, and readable text. It is not the right tool for setting a boolean DOM property or an object property.', example: `export class Welcome {\n  name = 'Ada';\n  unread = 3;\n}\n\n<h1>Welcome, {{ name }}!</h1>\n<p>You have {{ unread }} messages.</p>`, notes: ['Angular escapes interpolated text to reduce XSS risk.', 'Keep expressions simple; prepare complex values in the class.'] },
      { title: 'Property binding: values into properties', explanation: 'Property binding uses square brackets to set a DOM property, directive input, or child component input. Unlike an HTML attribute, a property is a live value on the element. This matters for booleans such as disabled and for objects or numbers that should not become strings.', example: `<button [disabled]="isSaving()">\n  {{ isSaving() ? 'Saving...' : 'Save' }}\n</button>\n\n<app-course-card [course]="selectedCourse()" />`, notes: ['Use [disabled]="true", not disabled="true" for a dynamic boolean.', 'Do not write [class] when class binding or ngClass expresses the intent better.'] },
      { title: 'Event binding: user actions into the class', explanation: 'Event binding uses parentheses to listen to a DOM event or a child component output. Angular calls the expression when the event occurs. The special $event value contains the event object or emitted value. Keep event handlers small and delegate real work to a method or service.', example: `<button (click)="addToCart(course)">Add to cart</button>\n<input (input)="searchChanged($event)" />\n<app-card (selected)="openCourse($event)" />\n\nsearchChanged(event: Event) {\n  const input = event.target as HTMLInputElement;\n  this.query.set(input.value);\n}`, notes: ['Keyboard users need keyboard events or native controls, not only mouse events.', 'Do not put a long chain of side effects directly in the template.'] },
      { title: 'Two-way binding: a value and an event together', explanation: 'Two-way binding means the component reads a value and receives changes to that value. The banana-in-a-box syntax [(...)] is shorthand for a property binding plus a matching change event. For native form controls, ngModel requires FormsModule. For custom components, the input and output naming contract must match.', example: `<input [(ngModel)]="name" />\n<p>Hello {{ name }}</p>\n\n// Equivalent idea:\n<input [ngModel]="name"\n       (ngModelChange)="name = $event" />`, notes: ['Use reactive forms for larger forms and complex validation.', 'Two-way binding is convenient, but explicit input/output can make ownership clearer.'] },
      { title: 'Class, style, and attribute binding', explanation: 'Angular can bind CSS classes, inline styles, and HTML attributes. Use [class.active] for one class, [class] for a complete class value, [style.width.px] for a measured style, and [attr.aria-label] when the value is an attribute rather than a DOM property. Accessibility attributes often need attr binding.', example: `<article [class.featured]="course.isFeatured">\n  <div [style.width.%]="completion">{{ completion }}%</div>\n  <button [attr.aria-label]="'Open ' + course.title">Open</button>\n</article>`, notes: ['Prefer CSS classes for reusable visual states.', 'Use attribute binding for aria-* and data-* values.'] }
    ],
    questions: [
      q('Which binding displays a value as text?', ['Interpolation', 'Property binding', 'Route binding'], 0, 'Interpolation uses {{ value }} and is intended for text content.'),
      q('Why use [disabled] instead of disabled="false"?', ['The property receives a real boolean', 'It makes CSS faster', 'It creates a route'], 0, 'HTML attributes are strings; property binding can pass a boolean value.'),
      q('What is (click)="save()"?', ['Event binding', 'Interpolation', 'A pipe'], 0, 'Parentheses tell Angular to listen for an event and evaluate the expression.'),
      q('What does [(ngModel)] combine?', ['A value binding and a change event', 'Two services', 'A route and a guard'], 0, 'It is shorthand for binding the current value and listening for changes.'),
      q('Which binding is commonly needed for aria-label?', ['[attr.aria-label]', '[property.aria-label]', '{{ attr }}'], 0, 'ARIA values are HTML attributes, so attr binding is the explicit form.')
    ]
  },
  4: {
    sections: [
      { title: '@if and @else', explanation: 'Use @if when the DOM should exist only when a condition is true. Add @else if there is a meaningful alternative state. Conditions should describe visible UI states such as authenticated, loading, error, empty, or ready. Compute complicated conditions in TypeScript so the template remains readable.', example: `@if (user(); as currentUser) {\n  <p>Welcome, {{ currentUser.name }}</p>\n} @else {\n  <a routerLink="/login">Sign in</a>\n}`, notes: ['The as syntax stores the result for the block.', 'Do not forget the error and empty states when rendering remote data.'] },
      { title: '@for and track', explanation: '@for repeats a template for every item in a collection. track gives each item a stable identity so Angular can reuse DOM nodes when the collection changes. Use the database id or another truly stable key. If the list is editable, stable tracking also helps preserve focus and local element state.', example: `@for (course of courses(); track course.id; let index = $index) {\n  <li>\n    <span>{{ index + 1 }}. {{ course.title }}</span>\n  </li>\n} @empty {\n  <li>No courses found.</li>\n}`, notes: ['Avoid tracking by index when items can be inserted or sorted.', 'Use @empty to explain why a list has no visible rows.'] },
      { title: '@switch for multiple cases', explanation: 'Use @switch when one value selects from several mutually exclusive views. It is clearer than a long chain of unrelated conditions when the cases share one state variable. Always include a default case for unexpected values or future additions.', example: `@switch (status()) {\n  @case ('loading') { <app-spinner /> }\n  @case ('ready') { <app-results /> }\n  @case ('error') { <app-error /> }\n  @default { <p>Unknown state.</p> }\n}`, notes: ['Use an enum or union type for known states.', 'Keep each case small by delegating larger views to components.'] },
      { title: 'Rendering states as a design habit', explanation: 'A production component normally has more than a success state. Model loading, error, empty, partial, and ready states explicitly. This prevents blank screens and makes asynchronous behavior understandable. The control flow is not only syntax; it is a checklist for complete UX.', example: `@if (loading()) {\n  <app-skeleton />\n} @else if (error(); as message) {\n  <app-retry [message]="message" />\n} @else if (items().length === 0) {\n  <app-empty-state />\n} @else {\n  <app-list [items]="items()" />\n}`, notes: ['Give errors a retry path when retrying can help.', 'Do not show a spinner forever when a request has failed.'] }
    ],
    questions: [
      q('Why does @for need track?', ['To map data identity to DOM identity', 'To add a CSS animation automatically', 'To call an API'], 0, 'Stable identity lets Angular reuse the correct DOM nodes efficiently.'),
      q('When is @switch clearer than many @if blocks?', ['When one state value has several cases', 'When rendering one paragraph', 'When writing CSS'], 0, 'Switch communicates that the cases are alternatives for one value.'),
      q('What should a remote-data template include besides success?', ['Loading, error, and empty states', 'Only a larger font', 'A database schema'], 0, 'Users need feedback while data loads, when it fails, and when no data exists.')
    ]
  },
  5: {
    sections: [
      { title: 'Writable signals', explanation: 'signal creates a writable reactive value. Read it by calling it, update it with set when you have a replacement, and use update when the next value depends on the current value. Signals are synchronous values: reading a signal gives the current value immediately.', example: `count = signal(0);\n\nsetCount(value: number) {\n  this.count.set(value);\n}\n\nincrease() {\n  this.count.update(current => current + 1);\n}`, notes: ['Reading a signal requires count(), not count.', 'Prefer immutable updates for arrays and objects.'] },
      { title: 'Computed signals', explanation: 'computed creates a read-only value derived from signals it reads. Angular tracks those dependencies automatically. When a dependency changes, the computed value becomes stale and recalculates when read. This is the right place for totals, filtered lists, labels, and other derived values.', example: `items = signal<CartItem[]>([]);\nsubtotal = computed(() =>\n  this.items().reduce((sum, item) => sum + item.price, 0)\n);\n\nitemCount = computed(() => this.items().length);`, notes: ['Do not duplicate derived state in another writable signal.', 'Keep computed functions pure and predictable.'] },
      { title: 'Effects and external systems', explanation: 'effect runs when signals read inside it change. It is intended for side effects: logging, localStorage, analytics, or coordinating with a non-Angular library. It should not be used to keep two signals in sync; that creates hidden data flow and can cause loops.', example: `constructor() {\n  effect(() => {\n    localStorage.setItem('theme', this.theme());\n  });\n}`, notes: ['Browser APIs require a browser-safe rendering check in SSR apps.', 'A computed value is usually better than an effect for derived data.'] },
      { title: 'Signal inputs and outputs', explanation: 'Modern Angular components can use input and output functions to make component APIs reactive. input() creates a read-only signal supplied by the parent. input.required() documents a required value. output() creates a typed event emitter. This makes data flow visible and works naturally with computed values.', example: `course = input.required<Course>();\nselected = output<number>();\n\nlabel = computed(() =>\n  this.course().title.toUpperCase()\n);\n\nchoose() { this.selected.emit(this.course().id); }`, notes: ['The child should not mutate its input.', 'Emit intent and let the parent decide what state changes.'] }
    ],
    questions: [
      q('How do you read a signal called count?', ['count()', 'count', 'read.count'], 0, 'Signal reads are function calls so Angular can track the reactive dependency.'),
      q('Which API is best for derived values?', ['computed', 'effect', 'setInterval'], 0, 'computed expresses a read-only value derived from other reactive values.'),
      q('What is an effect for?', ['Synchronizing with an external system', 'Replacing every computed value', 'Declaring a CSS class'], 0, 'Effects are for side effects such as storage, logging, or third-party widgets.'),
      q('Can a child component mutate an input signal?', ['No, it should emit intent instead', 'Yes, any input is global', 'Only from CSS'], 0, 'Inputs belong to the parent. The child can emit an event describing what the user requested.')
    ]
  }
};
