import { Lesson } from './lesson.model';

const lesson = (
  id: number, level: string, title: string, summary: string, duration: string, tag: string,
  accent: string, concept: string, analogy: string, example: string, takeaway: string,
  question: string, options: string[], answer: number
): Lesson => ({ id, track: 'Node.js', level, title, summary, duration, tag, accent, concept, analogy, example, takeaway, quiz: { question, options, answer } });

export const nodeLessons: Lesson[] = [
  lesson(501, 'Start here', 'What is Node.js?', 'Understand JavaScript outside the browser, its strengths, and what Node is not.', '18 min', 'Foundations', 'coral',
    'Node.js is a runtime that lets JavaScript run on your computer or a server, powered by the V8 engine. It is excellent for network services, APIs, tools, automation, and streaming I/O. Node is not a framework and it is not a database; it is the environment in which your server-side JavaScript runs.',
    'The browser is a JavaScript apartment with browser-only facilities such as the DOM. Node.js is a workshop: it runs the same language but gives you files, processes, networks, and server tools instead.',
    `// hello.js\nconsole.log('Hello from Node.js');\n\n// Run in a terminal:\nnode hello.js\n\n// Node has no document or window object.\nconsole.log(process.version);`,
    'Node.js lets you use JavaScript to build the backend and developer tools, but it needs a framework or your own code to define an application.',
    'Where does Node.js normally run?', ['On a server or your computer', 'Only inside a browser tab', 'Only inside a database'], 0),
  lesson(502, 'Start here', 'Install Node and use the terminal', 'Set up Node safely, run scripts, and understand project folders.', '24 min', 'Setup', 'gold',
    'Install a current LTS release of Node.js, then verify node --version and npm --version. A terminal is how you run Node programs and project scripts. Learn a few commands: pwd to see where you are, ls to list files, cd to move, and mkdir to create a folder. Keep each project in its own directory.',
    'A terminal is a precise receptionist: it needs the right address and instruction, then it runs the task exactly as requested.',
    `# Verify the installation\nnode --version\nnpm --version\n\n# Create a project\nmkdir node-playground\ncd node-playground\nnpm init -y\nnode --eval "console.log('Ready!')"`,
    'Use an LTS Node version and always check which folder your command will affect before running it.',
    'Which command runs a JavaScript file with Node?', ['node app.js', 'npm browser app.js', 'javascript app.js'], 0),
  lesson(503, 'Start here', 'JavaScript you need for Node', 'Review modules, objects, arrays, functions, errors, and async/await before building servers.', '30 min', 'Essentials', 'blue',
    'Node uses modern JavaScript. Be comfortable with const and let, objects and arrays, destructuring, functions, template strings, try/catch, promises, and async/await. TypeScript is optional but common; first understand the JavaScript that Node actually executes.',
    'JavaScript is the language; Node is the kitchen where you use it to prepare server work.',
    `async function getGreeting(name) {\n  if (!name) throw new Error('Name is required');\n  return { message: \`Hello, \${name}!\` };\n}\n\ntry {\n  console.log(await getGreeting('Ada'));\n} catch (error) {\n  console.error(error.message);\n}`,
    'Clear functions, deliberate errors, and async/await are the core habits that make Node code readable.',
    'What does an async function return?', ['A Promise', 'Only a string', 'A database connection'], 0),
  lesson(504, 'Build the basics', 'npm and package.json', 'Install packages, define scripts, and understand dependencies without treating npm as magic.', '28 min', 'Tooling', 'mint',
    'npm is Node’s package manager. package.json describes your project: name, scripts, dependencies, and development dependencies. npm install adds runtime packages; npm install -D adds tools used only while developing. Commit package.json and package-lock.json, but do not commit node_modules.',
    'package.json is a recipe card; package-lock.json records the exact ingredients that were used.',
    `// package.json\n{\n  "type": "module",\n  "scripts": {\n    "dev": "node --watch src/server.js",\n    "start": "node src/server.js",\n    "test": "node --test"\n  }\n}\n\n# Add a package\nnpm install express\nnpm install -D eslint`,
    'Use npm scripts for repeatable work, and read a package’s documentation before adding it.',
    'Where do you define an npm script?', ['package.json', 'node_modules', 'index.html'], 0),
  lesson(505, 'Build the basics', 'Modules, imports, and exports', 'Split a Node application into small files with explicit public APIs.', '26 min', 'Architecture', 'violet',
    'Modules let one file export values and another import them. Modern Node supports ECMAScript modules (ESM) using import/export; set "type": "module" in package.json or use .mjs files. CommonJS uses require/module.exports and exists in older projects. Do not mix styles casually.',
    'Modules are rooms with labeled doors: export says what may leave the room, import says what a room needs from another.',
    `// src/math.js\nexport function add(a, b) { return a + b; }\n\n// src/app.js\nimport { add } from './math.js';\nconsole.log(add(2, 3));\n\n// Note: local ESM imports include .js.`,
    'Keep each module focused and make dependencies visible through imports.',
    'What does export do?', ['Makes a value available to other modules', 'Sends an HTTP response', 'Installs a package'], 0),
  lesson(506, 'Build the basics', 'Files, paths, and environment variables', 'Read and write files safely, build portable paths, and keep secrets out of source code.', '34 min', 'Node APIs', 'coral',
    'Node’s fs/promises API reads and writes files asynchronously. Use node:path to build paths instead of string concatenation. Environment variables arrive through process.env and are appropriate for configuration and secrets, but validate required values on startup. Never put .env files containing secrets in version control.',
    'The filesystem is a filing cabinet. Paths are the address labels, and environment variables are private instructions handed to the app when it starts.',
    `import { readFile } from 'node:fs/promises';\nimport path from 'node:path';\n\nconst file = path.join(process.cwd(), 'data', 'courses.json');\nconst text = await readFile(file, 'utf8');\nconst courses = JSON.parse(text);\n\nif (!process.env.DATABASE_URL) throw new Error('DATABASE_URL is required');`,
    'Treat input, paths, and configuration as boundaries: validate them before trusting them.',
    'Why use path.join rather than building paths with /?', ['It works correctly across operating systems', 'It encrypts files', 'It creates a database'], 0),
  lesson(507, 'Build the basics', 'Async I/O and the event loop', 'Learn why Node can serve many requests without waiting on file or network work.', '36 min', 'Runtime', 'gold',
    'Node runs JavaScript on a main thread but delegates many I/O operations—networking, file access, timers—to the operating system or worker pool. When that work finishes, callbacks and promise continuations are scheduled for JavaScript to handle. Blocking CPU-heavy loops delay every request, so use asynchronous APIs and move expensive CPU work to workers or another service.',
    'The event loop is a barista taking many orders: while one drink is brewing, the barista can take the next order; one very long task blocks the counter for everyone.',
    `import { readFile } from 'node:fs/promises';\n\nconsole.log('1: start');\nreadFile('notes.txt', 'utf8').then(() => console.log('3: file read'));\nconsole.log('2: keep serving work');\n\n// Avoid this in a request handler:\n// while (true) { /* CPU work blocks the server */ }`,
    'Async I/O makes Node responsive; it does not make CPU-heavy JavaScript free.',
    'What can a CPU-heavy loop do in a Node server?', ['Block other requests from being handled', 'Make disk reads asynchronous', 'Create a route automatically'], 0),
  lesson(508, 'Build real apps', 'HTTP fundamentals and the built-in server', 'Understand requests, responses, methods, URLs, headers, status codes, and JSON.', '38 min', 'Networking', 'blue',
    'HTTP is the language used by browsers and APIs. A request has a method, URL, headers, and sometimes a body. A response has a status code, headers, and body. Start by understanding Node’s built-in http module; frameworks make more sense once you know what they wrap.',
    'HTTP is a restaurant order slip: method says what you want done, URL names the item, headers add instructions, and the status code tells you the result.',
    `import http from 'node:http';\n\nconst server = http.createServer((req, res) => {\n  if (req.method === 'GET' && req.url === '/health') {\n    res.writeHead(200, { 'content-type': 'application/json' });\n    return res.end(JSON.stringify({ ok: true }));\n  }\n  res.writeHead(404).end('Not found');\n});\nserver.listen(3000, () => console.log('http://localhost:3000'));`,
    'A good API returns appropriate status codes and predictable JSON, including useful errors.',
    'Which status code means a requested resource was not found?', ['404', '200', '500'], 0),
  lesson(509, 'Build real apps', 'Build a REST API with Express', 'Create routes, middleware, JSON responses, and a clean application structure with Express.', '42 min', 'APIs', 'mint',
    'Express is a small web framework that maps requests to route handlers and composes middleware. Use express.json() before routes that read JSON bodies. Keep routing thin: routes parse HTTP concerns, services hold business rules, and repositories or data-access modules talk to storage.',
    'Express is a front desk that directs each request to the right specialist; middleware is the checklist every visitor passes through.',
    `import express from 'express';\nconst app = express();\napp.use(express.json());\n\napp.get('/api/courses', async (_req, res, next) => {\n  try { res.json(await courseService.list()); }\n  catch (error) { next(error); }\n});\n\napp.listen(3000);`,
    'Separate HTTP, business, and data concerns early so the app can grow without one giant server file.',
    'What middleware is needed before reading a JSON request body in Express?', ['express.json()', 'express.html()', 'node.parseJson()'], 0),
  lesson(510, 'Build real apps', 'Validation, errors, and API design', 'Protect your API with input validation, clear errors, pagination, and consistent response shapes.', '40 min', 'API Quality', 'violet',
    'Request data is untrusted—even if it came from your own frontend. Validate params, query strings, and bodies at the edge with a schema library such as Zod or Joi. Return 400 for invalid input, 401 for missing authentication, 403 for forbidden actions, 404 for missing resources, and 500 only for unexpected server failures. Never expose stack traces in production responses.',
    'Validation is a bouncer checking invitations before guests enter; error handling is a helpful host explaining what went wrong without revealing private back-office details.',
    `import { z } from 'zod';\nconst courseInput = z.object({ title: z.string().min(1).max(120) });\n\napp.post('/api/courses', async (req, res, next) => {\n  try {\n    const input = courseInput.parse(req.body);\n    res.status(201).json(await courseService.create(input));\n  } catch (error) { next(error); }\n});`,
    'Validate at the boundary, return errors a client can act on, and keep the internal cause in server logs.',
    'Why should a server validate data from its own frontend?', ['Clients and requests can be changed or forged', 'TypeScript validates every network request at runtime', 'Browsers cannot send invalid data'], 0),
  lesson(511, 'Build real apps', 'Databases and data access', 'Connect Node to persistent storage and avoid unsafe query construction.', '46 min', 'Data', 'coral',
    'A database persists data after the Node process stops. Relational databases such as PostgreSQL organize related data in tables and use SQL; document databases store flexible documents. Use a driver, query builder, or ORM, parameterize queries, manage connections through a pool, and model constraints in the database as well as the application.',
    'A database is the library archive, while your Node service is the librarian: it applies rules and fetches the right record without handing visitors the archive keys.',
    `import pg from 'pg';\nconst pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });\n\nexport async function findCourse(id) {\n  const result = await pool.query(\n    'SELECT id, title FROM courses WHERE id = $1', [id]\n  );\n  return result.rows[0] ?? null;\n}`,
    'Use parameterized queries and database constraints; never build SQL by joining untrusted strings.',
    'What protects a SQL query from injected values?', ['Parameterized query values', 'String concatenation', 'A prettier formatter'], 0),
  lesson(512, 'Go further', 'Authentication and authorization', 'Learn sessions, JWTs, password hashing, and why permission checks belong on the server.', '48 min', 'Security', 'gold',
    'Authentication answers “who is this?”; authorization answers “may they do this?”. Store passwords only as slow hashes using an audited library such as argon2 or bcrypt. Sessions keep an opaque identifier in a secure cookie; JWTs are signed tokens and need careful expiry and validation. Check permissions for every protected server action, not only in the Angular UI.',
    'Authentication is showing your badge at the door. Authorization is checking whether that badge opens this particular room.',
    `import argon2 from 'argon2';\nconst hash = await argon2.hash(password);\nconst valid = await argon2.verify(user.passwordHash, password);\n\nfunction requireAdmin(req, res, next) {\n  if (req.user?.role !== 'admin') return res.sendStatus(403);\n  next();\n}`,
    'Never store plain passwords or trust client-side role checks; the server is the authority.',
    'What is the difference between authentication and authorization?', ['Identity versus permission', 'CSS versus HTML', 'Reading versus writing files'], 0),
  lesson(513, 'Go further', 'Testing and debugging Node apps', 'Write unit and integration tests, inspect failures, and make behavior safe to change.', '42 min', 'Quality', 'blue',
    'Use the built-in node:test runner or a testing framework to check behavior. Unit-test pure business rules; integration-test routes with a test database or controlled dependencies. Make configuration injectable so tests do not depend on production services. Use a debugger, structured logs, and small reproduction cases rather than guessing at failures.',
    'Tests are rehearsal scenes: small ones practice individual moves, while integration tests rehearse how the cast works together.',
    `import test from 'node:test';\nimport assert from 'node:assert/strict';\nimport { add } from './math.js';\n\ntest('adds two values', () => {\n  assert.equal(add(2, 3), 5);\n});\n\n// Run: node --test`,
    'Test observable behavior and make failures easy to diagnose with context-rich logs.',
    'What is a good unit-test target?', ['A small deterministic business rule', 'A live production database', 'Random timing behavior'], 0),
  lesson(514, 'Go further', 'Security essentials for Node', 'Handle secrets, CORS, headers, rate limits, dependencies, and untrusted input responsibly.', '44 min', 'Security', 'mint',
    'Security is a set of layers: validate inputs, authenticate and authorize on the server, use HTTPS in production, protect secrets, set secure headers, configure CORS narrowly, rate-limit sensitive routes, and keep dependencies patched. Log safely—never log passwords, full tokens, or personal data. Security controls must match your product and threat model.',
    'A secure application is a house with several practical locks, not one giant lock on the front door.',
    `import helmet from 'helmet';\nimport rateLimit from 'express-rate-limit';\n\napp.use(helmet());\napp.use('/api/login', rateLimit({ windowMs: 60_000, max: 10 }));\napp.use(cors({ origin: 'https://your-frontend.example', credentials: true }));\n\n// Keep secrets in deployment configuration, never in git.`,
    'Build security into each boundary; a frontend check is helpful UX but never a permission system.',
    'Where should a production secret be stored?', ['Secure deployment environment configuration', 'A committed frontend file', 'A public Git repository'], 0),
  lesson(515, 'Go further', 'Deployment, observability, and performance', 'Run a Node API reliably in production with logs, health checks, graceful shutdown, and sensible scaling.', '46 min', 'Production', 'violet',
    'Production services need environment-specific configuration, structured logs, a health endpoint, monitoring, and graceful shutdown. On shutdown, stop accepting new connections and close database pools. Scale I/O-bound APIs with multiple processes or containers; profile before optimizing CPU bottlenecks. Use a reverse proxy or platform to terminate TLS and manage public traffic.',
    'Deployment is opening a restaurant for real customers: you need an address, opening checks, a way to observe problems, and a calm closing routine.',
    `const server = app.listen(process.env.PORT ?? 3000);\n\nprocess.on('SIGTERM', async () => {\n  server.close(async () => {\n    await pool.end();\n    process.exit(0);\n  });\n});\n\napp.get('/health', (_req, res) => res.json({ ok: true }));`,
    'A server is not finished when it starts locally—it is ready when it can be observed, stopped safely, and recovered in production.',
    'Why implement graceful shutdown?', ['To finish active work and release resources safely', 'To hide errors from logs', 'To make Node run in a browser'], 0),
  lesson(516, 'Go further', 'Build your first full Node project', 'Put the course together with a small, realistic API project plan and next steps.', '60 min', 'Project', 'coral',
    'Build a Course Notes API: users can list notes, create a note, update their own note, and delete it. Start with an in-memory array to learn HTTP, then add validation, a database, authentication, tests, and deployment one layer at a time. Keep the Angular frontend and Node API as separate applications that communicate through HTTP.',
    'A full project is a small town: routes are roads, services are public offices, the database is the archive, tests are inspections, and deployment is opening day.',
    `src/\n  server.js        # starts HTTP server\n  app.js           # Express setup and middleware\n  routes/notes.js  # HTTP routes\n  services/        # business rules\n  repositories/    # database access\n  middleware/      # auth and error handling\n\n# Milestone order: routes → validation → database → auth → tests → deploy`,
    'Build in thin, working slices. A small tested API you understand is more valuable than a large tutorial project you cannot explain.',
    'What is a sensible first milestone for an API project?', ['A small working route and testable behavior', 'Adding every package at once', 'Deploying before the app runs locally'], 0),
  lesson(517, 'Build real apps', 'Buffers, streams and file uploads', 'Process large files efficiently instead of loading everything into memory at once.', '42 min', 'Node APIs', 'blue',
    'A Buffer holds raw binary data. A stream handles data in small chunks over time, which is useful for large files, downloads, video, and uploads. Use pipeline to connect streams because it forwards errors and closes resources correctly. Treat uploaded file names and contents as untrusted input.',
    'A Buffer is one box of data. A stream is a conveyor belt: you can process each box without filling the whole warehouse first.',
    `import { createReadStream, createWriteStream } from 'node:fs';\nimport { pipeline } from 'node:stream/promises';\n\nawait pipeline(\n  createReadStream('large-report.csv'),\n  createWriteStream('report-copy.csv')\n);\n\n// The file moves in chunks instead of one huge read.`,
    'Use streams for big or continuous data, and use a small Buffer only when the data comfortably fits in memory.',
    'Why are streams useful for large files?', ['They process data in chunks and use less memory', 'They turn files into databases', 'They remove the need for validation'], 0),
  lesson(518, 'Build real apps', 'Workers, child processes and scheduled work', 'Keep CPU-heavy or long-running work away from web request handling.', '44 min', 'Runtime', 'mint',
    'A Node request handler should finish quickly. Use worker threads for CPU-heavy JavaScript work, child processes to run separate programs, and a job queue or scheduler for work that can happen later, such as emails or report generation. Never run an arbitrary shell command built from user input.',
    'Your API is the checkout counter. A worker is the stock room: slow packing work happens there so the queue at the counter keeps moving.',
    `import { Worker } from 'node:worker_threads';\n\nconst worker = new Worker(new URL('./resize-image.js', import.meta.url), {\n  workerData: { imageId: '42' }\n});\nworker.on('message', result => console.log(result));\nworker.on('error', console.error);`,
    'Move slow work out of the request path and give jobs retries, observability, and idempotent behavior.',
    'When is a worker thread a useful choice?', ['For CPU-heavy work that would block the event loop', 'For every small JSON response', 'To style an HTML button'], 0),
  lesson(519, 'Go further', 'WebSockets and real-time updates', 'Send live updates when polling an HTTP endpoint is not enough.', '40 min', 'Networking', 'violet',
    'HTTP is request/response. A WebSocket is a long-lived two-way connection, useful for chat, collaboration, live dashboards, and notifications. Authenticate the connection, validate every incoming message, limit message size and rate, and design reconnection because connections will drop.',
    'HTTP is sending letters back and forth. A WebSocket is a phone call that stays open while both people need to talk.',
    `// Browser client idea\nconst socket = new WebSocket('wss://api.example.com/live');\nsocket.addEventListener('message', event => {\n  const update = JSON.parse(event.data);\n  console.log(update);\n});\n\n// Server: authenticate and validate every message before broadcasting it.`,
    'Choose real-time connections only when the user benefits from immediate updates; normal HTTP is simpler for most CRUD actions.',
    'What makes WebSockets different from normal HTTP requests?', ['They keep a two-way connection open', 'They only send HTML', 'They replace databases'], 0),
  lesson(520, 'Go further', 'Caching, queues and reliability', 'Make APIs faster and more resilient without returning stale or incorrect data.', '46 min', 'Production', 'gold',
    'Caching keeps a reusable result closer to the request, but it creates an invalidation problem: decide what can be cached, for how long, and how it is refreshed. Queues absorb bursts and run work later. Design handlers to be idempotent so repeating a job does not create duplicate side effects.',
    'A cache is a small shelf near the counter for common items. A queue is a ticket rail that keeps a rush of orders organized.',
    `const cache = new Map();\n\nasync function getCourse(id) {\n  if (cache.has(id)) return cache.get(id);\n  const course = await repository.find(id);\n  cache.set(id, course);\n  setTimeout(() => cache.delete(id), 60_000);\n  return course;\n}\n\n// Production systems commonly use a shared cache such as Redis.`,
    'Cache only when measurement shows a benefit, and be explicit about expiry, invalidation, and safe retries.',
    'What question must every cache design answer?', ['When and how cached data becomes invalid', 'Which CSS selector to use', 'How to avoid all tests'], 0),
  lesson(521, 'Go further', 'Docker and containers for Node', 'Package an API with its runtime so it behaves consistently across environments.', '44 min', 'Deployment', 'coral',
    'A container packages the Node runtime, application, and declared dependencies into an image. A Dockerfile describes how to build it. Use a small official Node image, copy dependency manifests before source code for cache efficiency, set NODE_ENV, run as a non-root user when possible, and keep secrets outside the image.',
    'A container is a labeled lunchbox containing exactly the runtime and ingredients your service needs—without bringing along your whole kitchen.',
    `FROM node:22-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci --omit=dev\nCOPY src ./src\nENV NODE_ENV=production\nUSER node\nCMD ["node", "src/server.js"]\n\n# Build: docker build -t course-api .`,
    'A container improves consistency, but it does not replace secure configuration, monitoring, or application tests.',
    'What should not be baked into a Docker image?', ['Production secrets', 'Your application source code', 'The Node runtime'], 0)
];
